"""Cut planning that keeps every source clip on the timeline at or under MAX_SHOT_SEC.

The Streamlit preview and the CapCut builder share these steps so they agree:

1. group_units_into_shots(): text first. Caption-sized meaning units are merged
   into the fewest cuts that each fit under the cap, using the measured TTS
   length when available and a speech-rate estimate otherwise. Cut points stay
   on meaning boundaries, so every cut can get a source that fits its words.
2. split_shot_timeline(): with the real TTS length, every cut gets its share of
   the sentence. A cut that still runs over the cap is split evenly.
3. resolve_shot_placements(): turns cuts into concrete source windows. Clips play
   at native speed where possible; when a clip is shorter than its cut, the next
   candidate fills the rest (or a gentle slow motion covers a small shortfall).
"""

from __future__ import annotations

import math
import os
from dataclasses import dataclass
from itertools import combinations
from typing import Callable, Dict, List, Optional, Sequence

MAX_SHOT_SEC = 3.0
# Effective characters per second at 1.0x (naver_clip_adforge.calculate_effective_speech_length).
# Drafts generated by this tool measured 7.3-8.9; the lower value keeps the preview
# conservative, and the builder re-splits with the real audio length anyway.
SPEECH_CHARS_PER_SEC = 7.0
TTS_TAIL_SEC = 0.3          # preserve_tts_ending() pads every sentence with 300 ms
MIN_SOURCE_US = 200_000     # clips shorter than this are skipped
MIN_PIECE_US = 400_000      # shortest extra cut added when a clip runs out
MIN_SLOWMO_SPEED = 0.6      # slower than this looks broken, so another clip fills in
REPEAT_JUMP_US = 500_000    # skip ahead when the same clip is cut back-to-back
MAX_FILL_STEPS = 8          # safety bound for filling one cut with short clips
STILL_IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp"}
_EXHAUSTIVE_LIMIT = 10      # sentences with more units fall back to greedy grouping


def estimate_sentence_seconds(weight_total: float, speech_speed: float = 1.0) -> float:
    """Rough TTS length of a sentence from its effective character count."""
    rate = SPEECH_CHARS_PER_SEC * max(0.1, float(speech_speed or 1.0))
    return max(0.0, float(weight_total)) / rate + TTS_TAIL_SEC


def _shares(weights: Sequence[float], total: float) -> List[float]:
    clean = [max(0.0, float(w)) for w in weights]
    total_w = sum(clean)
    if total_w <= 0:
        return [total / len(clean)] * len(clean)
    return [total * w / total_w for w in clean]


def group_units_into_shots(
    weights: Sequence[float], total_sec: float, max_sec: float = MAX_SHOT_SEC
) -> List[List[int]]:
    """Merge consecutive meaning units into the fewest cuts that each fit in max_sec.

    Among partitions with the same number of cuts, the most even one wins. A unit
    that alone runs over max_sec becomes its own cut; split_shot_timeline() breaks
    it up later.
    """
    n = len(weights)
    if n == 0:
        return []
    durations = _shares(weights, float(total_sec))
    limit = float(max_sec) + 1e-6

    def fits(start: int, end: int) -> bool:
        return end - start == 1 or sum(durations[start:end]) <= limit

    if n <= _EXHAUSTIVE_LIMIT:
        best = None
        for boundary_count in range(n):
            for inner in combinations(range(1, n), boundary_count):
                bounds = (0, *inner, n)
                pairs = list(zip(bounds, bounds[1:]))
                if not all(fits(a, b) for a, b in pairs):
                    continue
                spans = [sum(durations[a:b]) for a, b in pairs]
                key = (-min(spans), max(spans))
                if best is None or key < best[0]:
                    best = (key, bounds)
            if best is not None:
                break  # fewest cuts found
        bounds = best[1]
    else:
        bounds = [0]
        acc = 0.0
        for idx, duration in enumerate(durations):
            if idx > bounds[-1] and acc + duration > limit:
                bounds.append(idx)
                acc = 0.0
            acc += duration
        bounds.append(n)
    return [list(range(a, b)) for a, b in zip(bounds, bounds[1:])]


@dataclass(frozen=True)
class TimelineCut:
    shot_index: int      # planned cut this piece belongs to
    part: int            # 0 for the first piece of that planned cut
    start_us: int        # relative to the sentence start
    duration_us: int


def split_shot_timeline(total_us: int, weights: Sequence[float], max_us: int) -> List[TimelineCut]:
    """Spread the sentence audio over the planned cuts and split any cut over max_us."""
    total_us = int(total_us)
    if total_us <= 0 or not weights:
        return []
    max_us = max(1, int(max_us))
    clean = [max(0.0, float(w)) for w in weights]
    weighted = sum(clean) > 0
    total_w = sum(clean) if weighted else float(len(clean))
    bounds = [0]
    acc = 0.0
    for idx, weight in enumerate(clean):
        acc += weight if weighted else 1.0
        bounds.append(total_us if idx == len(clean) - 1 else int(round(total_us * acc / total_w)))

    cuts: List[TimelineCut] = []
    for shot_index, (start, end) in enumerate(zip(bounds, bounds[1:])):
        length = end - start
        if length <= 0:
            continue
        parts = max(1, math.ceil(length / max_us))
        base, extra = divmod(length, parts)
        cursor = start
        for part in range(parts):
            piece = base + (1 if part < extra else 0)
            cuts.append(TimelineCut(shot_index, part, cursor, piece))
            cursor += piece
    return cuts


@dataclass(frozen=True)
class Placement:
    path: str
    shot_index: int
    start_us: int              # relative to the sentence start
    duration_us: int           # length on the timeline, never longer than its cut
    source_start_us: int
    source_duration_us: int    # shorter than duration_us means gentle slow motion

    @property
    def speed(self) -> float:
        return self.source_duration_us / self.duration_us if self.duration_us else 1.0


def is_still_image(path: str) -> bool:
    return os.path.splitext(path)[1].lower() in STILL_IMAGE_EXTENSIONS


def _rotated_pick(pool: List[str], part: int, avoid: Sequence[Optional[str]]) -> str:
    start = part % len(pool)
    ordered = pool[start:] + pool[:start]
    return next((path for path in ordered if path not in avoid), ordered[0])


def resolve_shot_placements(
    cuts: Sequence[TimelineCut],
    sources_per_shot: Sequence[Sequence[str]],
    media_duration_us: Callable[[str], Optional[int]],
    usage: Optional[Dict[str, int]] = None,
    previous_path: Optional[str] = None,
    following_path: Optional[str] = None,
) -> List[Placement]:
    """Choose a concrete source window for every cut.

    sources_per_shot[i] lists candidates for planned cut i, best first; the first
    one is the user's pick. Extra pieces of a split cut rotate through the
    alternates, skipping the clip just shown and the clip the next cut opens with
    (following_path covers the next sentence). usage maps path -> next unused
    offset (µs), so a clip that comes back later shows new footage. Planned cuts
    without candidates stay empty.
    """
    usage = {} if usage is None else usage
    pools: List[List[str]] = []
    for raw in sources_per_shot:
        pool: List[str] = []
        for path in raw or []:
            if path and path not in pool and (media_duration_us(path) or 0) >= MIN_SOURCE_US:
                pool.append(path)
        pools.append(pool)

    placements: List[Placement] = []
    prev = previous_path
    for cut_pos, cut in enumerate(cuts):
        pool = pools[cut.shot_index] if cut.shot_index < len(pools) else []
        if not pool:
            continue
        if cut.part == 0:
            first = pool[0]
        else:
            upcoming = following_path
            if cut_pos + 1 < len(cuts):
                nxt = cuts[cut_pos + 1]
                next_pool = pools[nxt.shot_index] if nxt.shot_index < len(pools) else []
                upcoming = next_pool[0] if nxt.part == 0 and next_pool else None
            first = _rotated_pick(pool, cut.part, (prev, upcoming))
        queue = [first] + [p for p in pool if p != first]

        remaining, cursor, step = cut.duration_us, cut.start_us, 0
        while remaining > 0:
            path = queue[step % len(queue)]
            step += 1
            if is_still_image(path):
                use, src_start, src_len = remaining, 0, remaining
            else:
                total = int(media_duration_us(path) or 0)
                offset = usage.get(path, 0) + (REPEAT_JUMP_US if path == prev else 0)
                if offset + remaining > total:
                    offset = 0
                avail = total - offset
                if avail >= remaining:
                    use, src_len = remaining, remaining
                elif (avail >= remaining * MIN_SLOWMO_SPEED
                      or remaining - avail < MIN_PIECE_US
                      or step >= MAX_FILL_STEPS):
                    use, src_len = remaining, avail
                else:
                    use, src_len = avail, avail
                src_start = offset
                usage[path] = src_start + src_len
            placements.append(Placement(path, cut.shot_index, cursor, use, src_start, src_len))
            cursor += use
            remaining -= use
            prev = path
    return placements
